M48
; DRILL file {KiCad (6.0.2)} date Thu Jun 23 10:44:57 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-23T10:44:57-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.923
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.250
%
G90
G05
T1
X80.15Y-24.975
T2
X72.15Y-24.975
T3
X97.92Y-77.87
X108.08Y-77.87
T0
M30
